//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class PapilioSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PapilioSettings defaultInstance = ((PapilioSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PapilioSettings())));
        
        public static PapilioSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PapilioPort {
            get {
                return ((string)(this["PapilioPort"]));
            }
            set {
                this["PapilioPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PapilioBaudRate {
            get {
                return ((string)(this["PapilioBaudRate"]));
            }
            set {
                this["PapilioBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PapilioDataBits {
            get {
                return ((string)(this["PapilioDataBits"]));
            }
            set {
                this["PapilioDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PapilioParity {
            get {
                return ((string)(this["PapilioParity"]));
            }
            set {
                this["PapilioParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PapilioStopBits {
            get {
                return ((string)(this["PapilioStopBits"]));
            }
            set {
                this["PapilioStopBits"] = value;
            }
        }
    }
}
